### ISSUE TITLE
Allowing bound socket in Tcp.connect ?

### ISSUE THREAD

**Issue by psteckler** [janestreet/async_extra#14]
I want to have a client connect with a socket bound to a particular IP address. For example, I might want to have the IP address be `127.0.0.8` instead of the default localhost IP.

`Tcp.connect` expects the socket to be `Unconnected`, rather than `Bound`, though. I can use `Async.Socket.connect` instead, but then I lose things like the timeout feature of `Tcp.connect`.

Any chance of removing this restriction?

**Comment by snowleopard** [comment]
@psteckler It appears that after this issue was created, the library was refactored and `Tcp.connect` moved to [async_unix](https://github.com/janestreet/async_unix).

`Tcp.connect` accepts the argument `where_to_connect`, which can be created using [`of_host_and_port`](https://github.com/janestreet/async_unix/blob/ca8414c6fc5493870ec551c294a5399a217585a4/src/tcp.mli#L22) where I suppose you can specify `127.0.0.8` as the desired IP address.

I'm closing this issue but feel free to reopen it if needed, ideally, in the `async_unix` repository to make it more visible.
